### PR TITLE
Login and related forms and submit post form design changes

### PR DESCRIPTION
**Pull request by BoringBuffalo**
Made login/register/resend_confirmation/password_reset/password_recovery look more aligned/cohesive.

Made submit a post form cohesive, aligned, ordered the post types, replaced ordered list for polls with labels.

Got rid of spaces that ruined alignment.

Accidentally reformatted the main.css, sorry.

### CODE REVIEW

**Comment by happy-river** [comment]
The light gray background box works better for the submit post and resend confirmation forms then it does for login and register and I think that's because the narrower forms end up with a lot more empty space on the left side than the right side and that makes them look unbalanced.

I noticed in the course of clicking around that we put placeholder text in the input boxes for the login form but not for register/resend/recover.  One thing some sites do is omit the labels and just use placeholder text and that might be something to try to make our forms look more modern.  

> Accidentally reformatted the main.css, sorry

Having consistent formatting for main.css is an improvement but I'd prefer to see it as two commits, one that's just whitespace and one with the style changes.

**Comment by BoringBuffalo** [comment]
I'm not sure what we should do about login forms etc and their background/label whitespace. I think leaving them white when they have the list of links below is weird, the list is just floating in nothingness, unassociated. The label width is part of the pure-css system and changing any of their attributes has made other parts wonky, but might be the thing to do for these, I gave all the register etc forms a same class, it would look ideal if the labels were as wide as their content.

Omitting labels for placeholder text is considered bad for users because it requires people to remember things. Unless you're doing inline labels that don't disappear when people click into the box, but then we'd need big chonky boxes. The fields are also part of the pure-css system though.

We need to make sure all the form fields have placeholders and for attributes but I was going to do that in my next pass.

If I hasn't accidentally reformatted the css in the middle of all the changes I made I would have undid the formatting entirely. I can pick out the changes if it's needed.

**Comment by BoringBuffalo** [comment]
Actually I'm going to take back what I said about changing the label width. If it weren't for the TOS box, the labels and the fields would be the same size, even with the TOS it's still close. This makes the area between the labels and the fields, which is where people's eyes are going back and forth, close to the center of the form. I think that is ideal. Changing the label width of the small forms means putting the center of where people are looking in a random, off-centered location.

**Review by Polsaker — APPROVED** [review]
Looks good to me.
It'd be nice if we standardized the forms (I'd just remove all the placeholders and only use them for sample text instead of just the label text again)

It might be nice to discuss later if we should merge the login and registration pages into a single one

**Pull request merged**
