### PR TITLE
Add in "speaking as" concept

### PR DESCRIPTION
**Pull request by ferocious-ferret**
Allows Moderators and Admins to "distinguish" their posts and comments
So that they show up with an alternate style, so that mods and admins
stop looking like busy bodies when they tell people what to do.

### CODE REVIEW

**Comment by Polsaker** [comment]
Looks pretty good. An issue I found while testing is that I, being an admin cannot distinguish my comment as admin in a sub that I also moderate, and since admins are implicitly mods of all default subs it's not possible to distinguish a comment as admin in any default subs.

**Comment by ferocious-ferret** [comment]
> Looks pretty good. An issue I found while testing is that I, being an admin cannot distinguish my comment as admin in a sub that I also moderate, and since admins are implicitly mods of all default subs it's not possible to distinguish a comment as admin in any default subs.

So, this was a design decision that was made, but I agree it has some issues.

I had noticed in other places we had people using the least power they had in that area to take an effect, such as deleting a post, and so I replicated that here...

The options for this are really add in another button or ???

I'm not sure what the right answer is to be honest, I guess it's another button, but it feels so ugh to have two buttons that do the same thing for admins...

Do you have any thoughts on the right answer here?

**Comment by Polsaker** [comment]
> I had noticed in other places we had people using the least power they had in that area to take an effect, such as deleting a post, and so I replicated that here...

I can imagine some cases where it might be useful to speak as admin instead of as a mod 

> I'm not sure what the right answer is to be honest, I guess it's another button, but it feels so ugh to have two buttons that do the same thing for admins...

Yeah I agree there. Maybe an inline prompt similar to the "Are you sure? yes/no" ones. It'd be a trivial modification to the `TextConfirm` function to set the text for the yes/no part

**Comment by ferocious-ferret** [comment]
Take a look, let me know what you think

Added in the TextConfirm, and just made it so that it read in a mostly reasonable way rather than trying to get a different label in, but that is also a change that obviously could be made.

**Review by Polsaker — APPROVED** [review]

**Pull request merged**
